common: Add test categorization
eclipse-dataspaceconnector/DataSpaceConnector pull request #1034
Opened 2022-03-31 12:57 UTC by ouphi

## What this PR changes/adds

_Briefly describe WHAT your pr changes, which features it adds/modifies._

## Why it does that

_Briefly state why the change was necessary._

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Linked Issue(s)

Closes # <-- _insert Issue number if one exists_

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

2022-04-07 06:22 UTC, paullatzelsperger approved these changes
Could you document the intended usage of the various test types in `docs/developer/testing.md`? Other than that, I'm good with it.

2022-04-07 13:39 UTC, ouphi commented
> Could you document the intended usage of the various test types in `docs/developer/testing.md`? Other than that, I'm good with it.

Yes I documented the various tests in [testing.md](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1034/files#diff-c22885d97fa21ad974a3f5f982d92b6f45edc251fd34bc14223492ebd7391245)

2022-04-07 13:49 UTC, juliapampus requested changes

2022-04-07 13:49 UTC, juliapampus commented on CHANGELOG.md
> +* Added ComponentTest and EndToEndTest annotation (#?)
```suggestion
* Add ComponentTest and EndToEndTest annotation (#1034)
```

2022-04-07 18:51 UTC, jimmarino approved these changes

2022-04-08 07:20 UTC, juliapampus approved these changes

2022-04-08 07:20 UTC, merged