datamanagement: deprecate control api
eclipse-dataspaceconnector/DataSpaceConnector pull request #1113
Opened 2022-04-11 10:41 UTC by ndr-brt

## What this PR changes/adds

Add `@Deprecate` annotations on `control` api module.
Introduce data-management-api on `system-tests.e2e-transfer-test` module.

## Why it does that

We need to migrate to the old `control` api to the new `data-management` one.

## Further notes

Replacing all the `control` api occurrences seems like to much for a single PR, so it will be addressed to other PRs. 

## Linked Issue(s)

Ref #813 

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [x] documented public classes/methods?
- [x] added/updated relevant documentation?
- [x] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

2022-04-11 11:01 UTC, algattik commented on system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/dataspaceconnector/test/e2e/EndToEndTransferTest.java
> +//@EndToEndTest
```suggestion
@EndToEndTest
```

2022-04-11 14:23 UTC, ndr-brt commented
EDIT: replaced all the occurrencies of `control` api module in modules and tests

2022-04-12 07:23 UTC, paullatzelsperger reviewed
Can we just flat-out *delete* the `extensions:api:control` module? It would be a breaking change, but I'd say that's acceptable at the current stage.

2022-04-12 07:33 UTC, ndr-brt commented
@paullatzelsperger will do, the only issue is that this PR, since it updates the end to end test, fix also a bug about the validation of a new contract negotiation initialization, and that needs to be delivered with the milestone-3 (with a patch tag or something like this), but don't know it that's the case to include the `control` api removal into that tag. no problems from my side, just wondering.

2022-04-12 07:38 UTC, juliapampus commented
> AFAIK the milestone3 tag is already created.

@paullatzelsperger There is a need for creating a new tag with this fixed m3.

> The safest way would then be to merge this, and directly create another PR which deletes the `control` module.

+1

2022-04-12 07:41 UTC, ndr-brt commented
@paullatzelsperger @juliapampus open an issue not to forget:
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1116

2022-04-12 07:43 UTC, paullatzelsperger approved these changes

2022-04-12 07:46 UTC, florianrusch-zf requested changes
Found some missing references regarding the removement of the `auth-tokenbased` module as default auth-mechanism of the `DataManagementApi`

2022-04-12 07:46 UTC, florianrusch-zf commented on system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/local/FileTransferIntegrationTest.java
> +    public static final String CONSUMER_CONNECTOR_MANAGEMENT_URL = "http://localhost:" + CONSUMER_MANAGEMENT_PORT;
The constant in line 61 is not needed regarding the lag of the `auth-tokenbased` module in the dependencies of the control plane

2022-04-12 07:46 UTC, florianrusch-zf commented on system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/utils/FileTransferSimulationUtils.java
> +    private static ChainBuilder startContractAgreement(String providerUrl, String apiKey) {
The second argument is not needed regarding the lag of the `auth-tokenbased` module in the dependencies of the control plane

2022-04-12 07:46 UTC, florianrusch-zf commented on system-tests/tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/utils/FileTransferSimulationUtils.java
> +                .header(API_KEY_HEADER, apiKey)
This line is not needed

2022-04-12 14:34 UTC, florianrusch-zf commented on samples/04.1-file-transfer-listener/README.md
> +Assuming you didn't change the config files, the consumer will expose data-management api on port 9192 and the custom
```suggestion
Assuming you didn't change the config files, the consumer will expose data-management api on port `9192` and the custom 
```

2022-04-12 14:37 UTC, florianrusch-zf approved these changes

2022-04-12 15:48 UTC, cpeeyush commented on system-tests/runtimes/file-transfer-consumer/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ConsumerApiController.java
>      public Response initiateTransfer(@PathParam("filename") String filename, @QueryParam("connectorAddress") String connectorAddress,
okay, let me know if you already planning to make this change or should we pick it up under issue #1120

2022-04-12 15:54 UTC, cpeeyush approved these changes

2022-04-13 08:14 UTC, ndr-brt commented on system-tests/runtimes/file-transfer-consumer/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ConsumerApiController.java
>      public Response initiateTransfer(@PathParam("filename") String filename, @QueryParam("connectorAddress") String connectorAddress,
Definitely better to do that in another PR, since this solves also a bug and better to have it merged asap

2022-04-13 08:15 UTC, ndr-brt commented
@juliapampus ready for merge

2022-04-13 08:22 UTC, merged