docs: add decision records for serialization contexts
eclipse-dataspaceconnector/DataSpaceConnector pull request #1582
Opened 2022-07-04 08:54 UTC by juliapampus

## What this PR changes/adds

Adds a decision record for issue #1581.

## Why it does that

Document thoughts and concepts.

## Further notes

PR containing the implementation will follow.

## Linked Issue(s)

Related #1581 

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

2022-07-04 12:10 UTC, paullatzelsperger reviewed
To my understanding customizable serializers are intended purely for connector-to-connector communication.

For external communication (=APIs) we should continue to pursue the DTO concept.

2022-07-04 20:57 UTC, jimmarino commented
> To my understanding customizable serializers are intended purely for connector-to-connector communication.
> 
> 
> 
> For external communication (=APIs) we should continue to pursue the DTO concept.

They should work hand-in-hand. The serializers are to control how serialization is done and configured.

2022-07-06 12:03 UTC, ndr-brt approved these changes

2022-07-06 12:19 UTC, ronjaquensel approved these changes

2022-07-06 15:19 UTC, paullatzelsperger requested changes

2022-07-06 15:19 UTC, paullatzelsperger commented on docs/developer/decision-records/2022-07-04-type-manager/README.md
> +To being able to adjust or replace (de-)serialization of objects to Strings and vice versa for specific
```suggestion
Being able to adjust or replace (de-)serialization of objects and vice versa for specific
```

2022-07-06 15:19 UTC, paullatzelsperger commented on docs/developer/decision-records/2022-07-04-type-manager/README.md
> +extensions or added properties (e.g., caused by a domain-specific extension of an `Asset`), the `TypeManager`
```suggestion
extensions or added properties (e.g. required by a domain-specific extension of an `Asset`), the `TypeManager`
```

2022-07-06 15:19 UTC, paullatzelsperger commented on docs/developer/decision-records/2022-07-04-type-manager/README.md
> +This feature and decision targets the adaptability to existing interfaces and systems and the interoperability
```suggestion
This feature targets the adaptability to existing interfaces and systems and the interoperability
```

2022-07-06 15:19 UTC, paullatzelsperger commented on docs/developer/decision-records/2022-07-04-type-manager/README.md
> +requirements within varying data spaces. What is not intended is customization on a level that e.g. each
```suggestion
requirements within different data spaces. The goal is not to enable customization on the API level, such that e.g. each
```
(each dataspace in itself does not vary...)

2022-07-06 15:32 UTC, paullatzelsperger approved these changes

2022-07-07 06:27 UTC, merged