Replace MetadataStore with AssetIndex
eclipse-dataspaceconnector/DataSpaceConnector pull request #159
Opened 2021-10-18 12:29 UTC by ndr-brt

Ref #118 
The PR is still draft because there are some points I need help with:
* `DataEntry` could be completely replaced by `Asset` and deleted from the codebase?
* a mapping between a `List<Policy>` and `AssetSelectorExpression` is still missing (see `QueryEngineImpl`), how can we convert them?

2021-10-18 13:02 UTC, bscholtes1A commented on samples/04-file-transfer/api/src/main/java/org/eclipse/dataspaceconnector/extensions/api/ConsumerApiController.java
> +                .asset(Asset.Builder.newInstance().id(filename).property("policyId", "use-eu").build())
could be cool to reuse the POLICY_ID constant here (see my previous comment)

2021-10-18 13:03 UTC, bscholtes1A commented on samples/04-file-transfer/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/api/FileTransferExtension.java
> +        Asset asset = Asset.Builder.newInstance().id(assetId).property("policyId", USE_EU_POLICY).build();
POLICY_ID here again

2021-10-21 14:40 UTC, paullatzelsperger requested changes
Looks mostly fine to me, apart from a few minor nits.
However, we need to be really careful to replace all the `in-memory.metadata` references with `in-memory.asset-index` ones, otherwise stuff will break and we'll only notice that when e.g. trying to run the demos.

2021-10-21 14:40 UTC, paullatzelsperger commented on data-protocols/ids/ids-api-catalog/src/main/java/org/eclipse/dataspaceconnector/ids/api/catalog/CatalogQueryController.java
> +        return Response.ok(results.stream().map(Asset::getId).collect(toList())).build();
can we return `Asset`s here instead of strings?

2021-10-21 14:40 UTC, paullatzelsperger commented on extensions/in-memory/assetindex-memory/src/main/java/org/eclipse/dataspaceconnector/metadata/memory/InMemoryAssetIndex.java
> +    public void add(Asset asset, DataAddress address) {
feel free to do so, but we need to touch that again in [this issue](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/172) anyway

2021-10-21 14:40 UTC, paullatzelsperger commented on samples/04-file-transfer/consumer/build.gradle.kts
> +
The dependency will probably need to be replaced with the in-memory `AssetIndex`, right?

2021-10-21 14:40 UTC, paullatzelsperger commented on spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/transfer/DataRequest.java
> +    private Asset asset;
how about using the Asset-ID (i.e. a String)? Not much use in passing the whole asset object here. The only usage I could find was in `DataRequestMessageSender` and that only uses the Asset ID

2021-11-01 08:16 UTC, paullatzelsperger commented
I checked the samples 01-05 and fixed them exemplarily, I have a patch which I can send over, unfortunately I cannot attach it to this conversation directly. 
We will need to do that for all the other samples as well.

2021-11-02 08:45 UTC, mspiekermann commented
@paullatzelsperger and @ndr-brt So in combination with fix #200 (if it passes the last check) we can merge this PR to complete switching from `MetadataStore` to `AssetIndex`? Since this is related to many other issues it would be great to have this merged. In the meantime I will open a ticket to resolve #54 to allow I-test for all samples.

2021-11-02 15:56 UTC, paullatzelsperger commented
Lets do the following: 
 - lets merge in #201 which will make sure all the samples still can boot. 
 - then please rebase this PR onto `main` and force-push (which should trigger the sanity checks on CI) 
 - double-check locally that everything works
 - then me merge it. 
makes sense?

2021-11-02 16:25 UTC, ndr-brt commented
> Lets do the following:
> 
> * lets merge in [Feature/200 fix broken samples #201](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/201) which will make sure all the samples still can boot.
> * then please rebase this PR onto `main` and force-push (which should trigger the sanity checks on CI)
> * double-check locally that everything works
> * then we merge it.
>   makes sense?

Absolutely :+1:

2021-11-03 09:45 UTC, MoritzKeppler commented
#201  is merged, so please go ahead with rebase, @ndr-brt 
<sub> Moritz Keppler <moritz.keppler@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

2021-11-03 09:57 UTC, ndr-brt commented
Done, the check failed, but "it works on my machine" :)

2021-11-03 10:05 UTC, ndr-brt commented
I was able to replicate this `NullPointerException` locally: it happens when the process is killed before the service extensions are initialized. I just raise the sleep time to 10, not the best way but it should work.
What about catching exception on service extension's shutdown?
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/20acbd9c12dbe158286a3180bab8191a22632bb7/core/bootstrap/src/main/java/org/eclipse/dataspaceconnector/system/runtime/BaseRuntime.java#L145

2021-11-03 10:19 UTC, bscholtes1A commented
> I was able to replicate this `NullPointerException` locally: it happens when the process is killed before the service extensions are initialized. I just raised the sleep time to 10, not the best way but it should work.

Hi @ndr-brt 
for me a better approach would have been to have State associated with each Extension (WAITING, INITIALIZED, SHUTDOWN), so that we call the shutdown method only for extensions that are in the INITIALIZED state. But I am pretty sure this would be a huge change that can be handle there.

2021-11-03 10:22 UTC, ndr-brt commented
@bscholtes1A thanks for the advice, I think that should be good, but I was wrong, it does not work on my machine and the problem is another, I will fix that and push asap :+1:

2021-11-03 10:54 UTC, ndr-brt commented
@paullatzelsperger ready for merge

2021-11-03 12:45 UTC, merged