feat(Event Frame Work): add intermediate superclass for ContractNegotiation Events hierarchy
eclipse-dataspaceconnector/DataSpaceConnector pull request #1913
Opened 2022-09-02 07:18 UTC by janpmeyer

## What this PR changes/adds

Add a 'intermediate' superclass for the Event Payload Classes of the ContractNegotiation classes.

## Why it does that

Improve the work with the Event Framework and give the possibility to filter Events on a bigger group of events.

## Linked Issue(s)

Closes #1912

## Checklist

- [ ] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

2022-09-06 05:58 UTC, jimmarino commented on spi/common/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/event/contractnegotiation/ContractNegotiationEventPayload.java
> +public class ContractNegotiationEventPayload extends EventPayload {
Documentation

2022-09-06 05:59 UTC, jimmarino requested changes
Please add documentation

2022-09-13 13:08 UTC, janpmeyer commented
@jimmarino Documentation is adapted.

2022-09-13 13:37 UTC, ndr-brt approved these changes

2022-09-16 06:47 UTC, jimmarino approved these changes

2022-09-16 06:49 UTC, merged