Docs: add previous and next links to samples tutorial
eclipse-dataspaceconnector/DataSpaceConnector pull request #1929
Opened 2022-09-08 16:22 UTC by egekorkan

## What this PR changes/adds

Adds a Previous Chapter | Next Chapter links to each tutorial under samples

## Why it does that

Because it is not easy to navigate the tutorials without going back to the initial ToC or clicking a couple times through GitHub

## Further notes

## Linked Issue(s)

Closes #1822 

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

2022-09-08 16:24 UTC, egekorkan commented
Also @mspiekermann and @juliapampus from the discussion in #1822. I would also like to merge this before next week Tuesday since we are organizing an EDC hackathon/workshop.

2022-09-09 07:20 UTC, juliapampus requested changes

2022-09-09 07:20 UTC, juliapampus commented on samples/01-basic-connector/README.md
> +[Next Chapter](02-health-endpoint/README.md)
GitHub pages need a relative link

```suggestion
[Next Chapter](../02-health-endpoint/README.md)
```

2022-09-09 07:20 UTC, juliapampus commented on samples/01-basic-connector/README.md
> +<!-- ../02 seems to have the same behavior -->
```suggestion
```

2022-09-09 08:08 UTC, egekorkan commented on samples/01-basic-connector/README.md
> +[Next Chapter](02-health-endpoint/README.md)
done

2022-09-09 08:10 UTC, egekorkan commented
@juliapampus I have committed your suggestions

2022-09-09 08:15 UTC, juliapampus approved these changes

2022-09-09 08:15 UTC, merged