Feature/dataplane gcs
eclipse-dataspaceconnector/DataSpaceConnector pull request #2108
Opened 2022-10-18 07:49 UTC by git-masoud

## What this PR changes/adds

Adds the dataplane for google cloud storage.

## Why it does that

Enable data transfer from and to Google Cloud Storage.

## Further notes
 
Including some small fixes in the gcs-core and provisioner. Authentication is currently against the Google Cloud API.  Another pull request will come to cover different authentications' approaches. 

## Linked Issue(s)

Closes # <-- 1908

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

2022-10-18 10:13 UTC, paullatzelsperger commented
Hey @git-masoud, I have a suspicion why your CI is failing. A few classes like `ParallelSink` recently got refactored into a new module, and either your machine or our CI pipeline has not yet updated the dependencies. By default, Gradle updates devs every 24 hrs.

Could you try to invoke Gradle on your machine with `./gradlew clean build --refresh-dependencies`? If that works (i.e. no compile problems), it's likely that our CI runner has outdated dependencies and we'll have to wait for 24 hrs until we can re-trigger CI. You can do that yourself using `git commit -m "trigger CI" --allow-empty`, which would add an empty commit, which in turn triggers CI.

2022-10-18 10:17 UTC, git-masoud commented
> ./gradlew clean build --refresh-dependencies

I will do so. Thank you so much!

2022-10-18 12:17 UTC, ndr-brt requested changes

2022-10-18 12:17 UTC, ndr-brt commented on extensions/data-plane/data-plane-gcs/src/main/java/org/eclipse/dataspaceconnector/gcp/dataplane/gcs/validation/GcsSourceDataAddressValidationRule.java
> +        var composite = new CompositeValidationRule<>(
this could be a class field

2022-10-18 12:17 UTC, ndr-brt commented on extensions/data-plane/data-plane-gcs/src/main/java/org/eclipse/dataspaceconnector/gcp/dataplane/gcs/validation/GcsSinkDataAddressValidationRule.java
> +        var composite = new CompositeValidationRule<>(
this could be a class field, and it does not need to be a "composite" since there's only one rule (`EmptyValueValidationRule`)

2022-10-18 12:17 UTC, ndr-brt commented on extensions/data-plane/data-plane-gcs/src/main/java/org/eclipse/dataspaceconnector/gcp/dataplane/gcs/GcsDataSinkFactory.java
> +                .build().getService();
Code from line 77 to 96 is meant to build the `storageClient`, could it be moved into a separated method, this will make the code more readable

2022-10-19 07:29 UTC, git-masoud commented
since the project structure in the main branch was changed and there are many conflicts with this branch, I decided to close this PR and redoing it again because it will be faster.

2022-10-19 07:29 UTC, closed without merging