feat(dataplane gcs): add dataplane for Google Cloud Storage
eclipse-dataspaceconnector/DataSpaceConnector pull request #2112
Opened 2022-10-19 11:27 UTC by git-masoud

## What this PR changes/adds
Adds the dataplane for google cloud storage.

## Why it does that
Enable data transfer from and to Google Cloud Storage. 

## Further notes
Including some small fixes in the gcs-core and provisioner. Authentication is currently against the Google Cloud API. Another pull request will come to cover different authentications' approaches.

## Linked Issue(s)
Closes #1908 

## Checklist

- [X] added appropriate tests?
- [X] performed checkstyle check locally?
- [X] added/updated copyright headers?
- [ ] documented public classes/methods?
- [X] added/updated relevant documentation?
- [ ] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

2022-10-19 12:00 UTC, paullatzelsperger commented
@git-masoud have you signed the ECA? GH reports the check as `failed`...

2022-10-19 12:15 UTC, git-masoud commented
> @git-masoud have you signed the ECA? GH reports the check as `failed`...

yes, I have signed it. There is a weird issue. In the ECA check, I see two accounts are being verified. One as Masoud Allahyari(masoud.allahyari@****.com) which pass the tests, the other one is shown as Anonymous (masoud.allahyari@****.com) which is failing. I had my last commit directly in github, it could be the reason.

2022-10-19 12:50 UTC, ndr-brt requested changes

2022-10-19 12:50 UTC, ndr-brt commented on extensions/data-plane/data-plane-google-storage/src/main/java/org/eclipse/dataspaceconnector/gcp/dataplane/storage/GcsDataSinkFactory.java
> +        Storage storageClient = getStorageClient(destination.getKeyName());
please use `var`

2022-10-19 12:50 UTC, ndr-brt commented on extensions/data-plane/data-plane-google-storage/src/main/java/org/eclipse/dataspaceconnector/gcp/dataplane/storage/GcsDataSinkFactory.java
> +    private Storage getStorageClient(String keyName) {
`createStorageClient` would be more descriptive

2022-10-19 12:50 UTC, ndr-brt commented on extensions/data-plane/data-plane-google-storage/src/main/java/org/eclipse/dataspaceconnector/gcp/dataplane/storage/validation/GcsSinkDataAddressValidationRule.java
> +        var composite = new CompositeValidationRule<>(
this could be a class field

2022-10-19 12:50 UTC, ndr-brt commented on extensions/data-plane/data-plane-google-storage/src/main/java/org/eclipse/dataspaceconnector/gcp/dataplane/storage/validation/GcsSourceDataAddressValidationRule.java
> +        var composite = new CompositeValidationRule<>(
this could be a class field

2022-10-20 06:21 UTC, ndr-brt approved these changes

2022-10-21 13:39 UTC, paullatzelsperger approved these changes

2022-10-24 08:49 UTC, bscholtes1A approved these changes

2022-10-24 08:49 UTC, paullatzelsperger commented
> yes, I have signed it. There is a weird issue. In the ECA check, I see two accounts are being verified. One as Masoud Allahyari(masoud.allahyari@****.com) which pass the tests, the other one is shown as Anonymous (masoud.allahyari@****.com) which is failing. I had my last commit directly in github, it could be the reason.

I think the `user.email` of you git config and your git handle need to match the email of the ECA and the handle you specified there. 
I had problems with it too in the past :)

2022-10-24 09:09 UTC, merged

2022-10-24 09:09 UTC, paullatzelsperger commented
merged despite CodeQL Warnings - they are false positives and surface due to a refactoring/renaming of directories and files.