Refactor CosmosTransferProcessStore extension to use newly introduce CosmosDbApi and add unit tests
eclipse-dataspaceconnector/DataSpaceConnector pull request #257
Opened 2021-11-18 10:09 UTC by bscholtes1A

2021-12-09 09:39 UTC, paullatzelsperger requested changes
The only major thing is the `@JsonUnwrapped` annotation on the `CosmosDocument`. 
We either need to make sure all the queries in all other CosmosDB-based stores still work, or we put a pin in it, revert it and solve it in a subsequent PR.

2021-12-09 09:39 UTC, paullatzelsperger commented on extensions/azure/transfer-process-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/CosmosTransferProcessStore.java
> +        failsafeExecutor.run(() -> cosmosDbApi.createItems(Collections.singletonList(document)));
should be `saveItem`

2021-12-09 09:39 UTC, paullatzelsperger commented on extensions/azure/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/cosmos/azure/CosmosDbApi.java
>      void createItems(Collection<CosmosDocument<?>> definitions);
can we rename this ` saveItems`?

2021-12-09 12:13 UTC, paullatzelsperger commented
This patch should take care of the @JsonUnwrapped stuff: https://gist.github.com/paullatzelsperger/6b467769958adc4c860bd76b1b8ca46f

2021-12-09 14:01 UTC, bscholtes1A commented on extensions/azure/transfer-process-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/transfer/store/cosmos/CosmosTransferProcessStore.java
> +        failsafeExecutor.run(() -> cosmosDbApi.createItems(Collections.singletonList(document)));
done

2021-12-09 14:01 UTC, bscholtes1A commented on extensions/azure/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/model/ContractDefinitionDocument.java
> +    protected ContractDefinitionDocument() {
outdated

2021-12-09 14:01 UTC, bscholtes1A commented on extensions/azure/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/cosmos/azure/CosmosDbApi.java
> +    void updateItem(Object item);
corrected

2021-12-10 13:35 UTC, paullatzelsperger approved these changes

2021-12-10 13:51 UTC, merged