Proposal: SQL based AssetIndex / AssetLoader
eclipse-dataspaceconnector/DataSpaceConnector pull request #908
Opened 2022-03-16 10:18 UTC by denisneuling

## What this PR changes/adds

This PR adds a technical proposal to realize a SQL based AssetIndex / AssetLoader.

## Linked Issue(s)

Closes #863 

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [x] added/updated relevant documentation?
- [ ] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

<sub> Denis Neuling <denis.neuling@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

2022-03-16 12:53 UTC, paullatzelsperger commented
just saw, that you already added the soft-delete, which is tracked in a separate issue (#814), which is not scoped for M3. While the effort is laudable, the problem with this is that the other SQL backends and storage technologies (CosmosDB, in-memory) will not have soft-delete for now, so for M3 the `SqlAssetIndex` will behave differently from the rest. 
To avoid that, I think we should skip the soft-delete feature for now.

2022-03-18 08:24 UTC, denisneuling commented
@paullatzelsperger Thanks for pointing this out - just saw the concerning interface had been extended and thought it would have been a good idea to already include this, but sure, let's carve out the removal functionality for now. 

As I am somewhat busy with other tasks I am handing over this PR to @bcronin90 - Would you like to continue on this?

2022-03-21 15:37 UTC, denisneuling commented on extensions/sql/asset/sql_asset_index_loader_proposal.md
> +    deleted BOOLEAN DEFAULT FALSE,
@bcronin90 This line also needs to be deleted if soft-delete is now within the scope of this PR.

2022-03-25 07:48 UTC, paullatzelsperger requested changes

2022-03-25 07:48 UTC, paullatzelsperger commented on extensions/sql/asset/sql_asset_index_loader_proposal.md
> +    asset_id VARCHAR(255) NOT NULL,
lets stick with `VARCHAR` and add a comment, that this DDL is only tested with Postgres. There really is no portable way for variable length text columns across multiple RDBMS. For example, `VARCHAR(MAX)` does not even work on Postgres.

2022-03-25 07:48 UTC, paullatzelsperger commented on extensions/sql/asset/sql_asset_index_loader_proposal.md
> +CREATE TABLE IF NOT EXISTS edc_asset_dataaddress (
```suggestion
CREATE TABLE IF NOT EXISTS edc_data_address (
```

2022-03-25 07:48 UTC, paullatzelsperger commented on extensions/sql/asset/sql_asset_index_loader_proposal.md
> +    property_object_value VARCHAR(MAX) DEFAULT NULL,
I guess `property_string_value` and `property_object_value` could be collated into one, given that we'll have a `property_type` field containing the java class name

2022-03-25 07:48 UTC, paullatzelsperger commented on extensions/sql/asset/sql_asset_index_loader_proposal.md
> +INSERT INTO edc_asset_property (asset_id, property_name, property_string_value) VALUES ("80b69de0-a50c-11ec-b909-0242ac120002", "asset:prop:name", "Seneca");
multiple `VALUES( ...)` expresseions can be chained, see [here](https://www.postgresqltutorial.com/postgresql-insert-multiple-rows)

2022-03-25 07:48 UTC, paullatzelsperger commented on extensions/sql/asset/sql_asset_index_loader_proposal.md
> +BEGIN;
We won't have to express transactions explicitly. That what we have the `TransactionContext` (and related classes) for.

2022-03-25 07:48 UTC, paullatzelsperger commented on extensions/sql/asset/sql_asset_index_loader_proposal.md
> +
Missing the `findById` case. Note: don't forget to join with data address and properties.

2022-04-07 05:54 UTC, jimmarino commented
@paullatzelsperger is this PR still relevant or has it been superseded?

2022-04-08 08:55 UTC, paullatzelsperger commented
> @paullatzelsperger is this PR still relevant or has it been superseded?

It's already implemented and documented, lets just close this.

2022-04-08 08:55 UTC, closed without merging